[tools]
bun = "1.2.20"

[hooks]
postinstall = "bun i"

[tasks.start]
description = "Run the application"
run = "bun run start"

[tasks.dev]
description = "Run the application in development mode"
run = "bun run dev"

[tasks.test]
description = "Run tests"
run = "bun run test"

[tasks.format]
description = "Format code with typecheck"
run = ["bun run format", "bun run typecheck"]
alias = "lint"
